### ISSUE TITLE
npm 経由の bootstrap ではモーダルのshow/hide イベントが発火しない

### ISSUE THREAD

**Issue by tanukiti1987** [yuuganisakase/cz-aga#15]
https://getbootstrap.jp/docs/4.2/components/modal/

モーダルを開くときのイベントが走らなくなり、ダイアログが正常に動いていない模様。

~~cdn を通した bootstrap のロードでなくなったところが影響しているかも。（調査中）~~

**Comment by tanukiti1987** [comment]
- jQuery は動いている
- `show.bs.modal` などのイベントだけが発火されない
- Propper の設定を webpack.dev に追加しても動かない
- bootstrap, jquery を cdn 経由に戻すと動く

色々試してみたのですが、エラーが出るわけでもなく、手がかりが掴みきれていない状態です。

**Comment by tanukiti1987** [comment]
related commit: https://github.com/yuuganisakase/cz-aga/commit/a54b5a87386ce307eea30576776408357ddc69e7

**Comment by yuuganisakase** [comment]
情報ありがとうございます！こちらでも調べてみます

**Comment by yuuganisakase** [comment]
いろいろためしてなおりました。

あまり自信ないですが
1. application.jsで jquery require
2. provideプラグインでグローバルjquery上書きされる
3. cdnでグローバルjquery上書きされる
という順番で、2を抜く必要があったという理解

https://github.com/yuuganisakase/cz-aga/commit/78110f193ba240ff317b38a836ce316b63178fc3

@tanukiti1987

**Comment by tanukiti1987** [comment]
@yuuganisakase 調査＆修正、ありがとうございました！
bootstrap が使っている jQuery が上書きされていたのですね 😓 そこまで察せられていればよかったのですが、すみません。。

修正後、動作的に問題ないことも確認しました！
こちらの issue クローズさせていただきます。
