### ISSUE TITLE
予約可否APIの作成

### ISSUE THREAD

**Issue by tanukiti1987** [yuuganisakase/cz-aga#4]
## [get,post] /api/bookings/check

予約可否情報を返す、時間複数指定
開始時間昇順ソート
時間パラメーター500くらい並ぶ
例： `/api/bookings/check?times[]=2021-03-01T13:00+09:00/PT1H&times[]=2021-03-01T14:00+09:00/PT1H`

response参考:
```
{
	status: "ok"
	results: [
		{
			time: "2021-03-01T13:00+09:00/PT1H",
			vacant: 2 # 空き枠数
		},
		{
			time: "2021-03-01T14:00+09:00/PT1H",
			vacant: 0
		}
	]
}
```

## 時間指定のフォーマット
ISO_8601
https://ja.wikipedia.org/wiki/ISO_8601#%E7%B6%99%E7%B6%9A%E6%99%82%E9%96%93
https://amg-solution.jp/blog/9491
スタート時間と継続時間で表す
format: `<start>/<duration>`
ex: `2021-03-01T13:00+09:00/PT1H`

## Todo

- [x] エンドポイントを用意する
- [x] ロジックの実装

##  その他

- POST リクエストは必要か？

**Comment by yuuganisakase** [comment]
ブラウザによってgetのクエリ文字数制限2083にひっかかるため、本番ではpostのほうが安全かという判断をしています。

**Comment by tanukiti1987** [comment]
- １時間以上期間が空いた予約枠について、予約空き枠の計算をする。それ以外は空き枠０とする
